name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
        - uses: actions/checkout@master
        - name: Use NodeJS
          uses: actions/setup-node@master
          with:
              node-version: ${{ matrix.node-version }}
              cache: 'npm'
              # cache-dependency-path: subdir/package-lock.json
        - run: npm install
        - run: npm run build
        - run: npm run test

    