name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@master
        - name: Use NodeJS
          uses: actions/setup-node@master
          with:
              node-version: '14'
              cache: 'npm'
              # cache-dependency-path: subdir/package-lock.json
        - run: npm install
        # - run: npm run test
        - run: npm run build

    